
# Generated by Django 3.0.2 on 2020-02-13 16:30




from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('availability', models.BooleanField(default=True, verbose_name='availability')),
                ('wigu', models.TextField(default='', verbose_name='wigu')),
                ('education', models.TextField(default='', verbose_name='education')),
                ('language', models.TextField(default='', verbose_name='language')),
                ('about', models.TextField(default='', verbose_name='about')),
                ('interest', models.TextField(default='', verbose_name='interest')),

                ('birthday', models.DateField(default=None, null=True)),

                ('link', models.TextField(default='', verbose_name='link')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is_verified')),
                ('civ', models.TextField(default='', verbose_name='civ')),
                ('cil', models.TextField(default='', verbose_name='cil')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_id', models.IntegerField()),
                ('comment', models.TextField(default='', verbose_name='comment')),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpaceRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Spaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('address', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
