# Generated by Django 3.0.2 on 2020-02-13 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=256)),
                ('KindofHome', models.CharField(max_length=15)),
                ('RoomType', models.CharField(max_length=15)),
                ('Capacity', models.PositiveIntegerField()),
                ('Description', models.TextField()),
                ('PlacePhoto', models.ImageField(blank=True, upload_to='static')),
                ('RequestedToRent', models.BooleanField(default=False)),
                ('rented', models.BooleanField(default=False)),
                ('Pets', models.BooleanField(default=False)),
                ('Kids', models.BooleanField(default=False)),
                ('SmokingAllowed', models.BooleanField(default=False)),
                ('HostLanguage', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Arrival', models.DateField()),
                ('Depart', models.DateField()),
                ('AcceptanceByHost', models.BooleanField(default=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='placeandbooking.Place')),
            ],
        ),
    ]
