# Generated by Django 3.0.2 on 2020-02-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeandbooking', '0002_auto_20200203_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='HostLanguage',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='PlacePhoto',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
