# Generated by Django 3.0.2 on 2020-02-14 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0002_memberevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='members',
            field=models.ManyToManyField(through='event.MemberEvent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='memberevent',
            unique_together={('event', 'account')},
        ),
    ]
